In [29]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from torch.utils.data import Dataset,DataLoader
from sklearn.model_selection import train_test_split

In [30]:
df = pd.read_csv('/kaggle/input/datasets/harshadapatil31/student-performance-and-study-habits-dataset/student_performance_dataset.csv')
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [31]:
df=df.drop('student_id',axis=True)

In [32]:
df['internet_access']=df['internet_access'].map({'Yes':1 ,'No':0})
df['extracurricular_activities']=df['extracurricular_activities'].map({'Yes':1 ,'No':0})
df['part_time_job']=df['part_time_job'].map({'Yes':1 ,'No':0})

In [33]:
df.isna().sum()

gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [34]:
df['parental_education']=df['parental_education'].fillna(df['parental_education'].mode()[0])

In [35]:
df.isna().sum()

gender                        0
study_time_hours              0
attendance_percent            0
sleep_hours                   0
parental_education            0
internet_access               0
extracurricular_activities    0
part_time_job                 0
previous_grade                0
final_exam_score              0
final_grade                   0
dtype: int64

In [36]:
lbl=LabelEncoder()
df['final_grade']=lbl.fit_transform(df['final_grade'])

In [37]:
df.head()

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,Male,4.0,98.0,6.5,Bachelors,1,1,0,76.9,100.0,0
1,Female,6.3,100.0,5.7,High School,1,1,1,75.5,100.0,0
2,Male,4.9,85.3,7.9,Bachelors,1,0,1,88.5,97.3,0
3,Male,2.6,77.5,8.0,High School,1,1,0,85.1,83.8,1
4,Male,2.2,89.6,4.6,Bachelors,1,0,1,61.8,68.3,3

In [38]:
X=df.drop('final_grade',axis=1)
y=df['final_grade']

In [39]:
Categorical_columns = ['gender']
Ordinal_columns = ['parental_education']
numeric_columns = [feature for feature in X if X[feature].dtype=='int' or X[feature].dtype=='float']
print(numeric_columns)

['study_time_hours', 'attendance_percent', 'sleep_hours', 'internet_access', 'extracurricular_activities', 'part_time_job', 'previous_grade', 'final_exam_score']

In [40]:
ohe=OneHotEncoder()
oe=OrdinalEncoder(categories=[['High School','Bachelors','Masters','PhD']])
scaler=StandardScaler()

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [42]:
preprocessor = ColumnTransformer([
    ("OneHotEncoder",ohe,Categorical_columns),
    ("OrdinalEncoder",oe,Ordinal_columns),
    ("StandardScaler",scaler,numeric_columns)
],remainder='passthrough')

In [43]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [44]:
feature_names = preprocessor.get_feature_names_out()

X_train_df = pd.DataFrame(
    X_train,
    columns=feature_names
)

In [45]:
X_train_df.head()

,OneHotEncoder__gender_Female,OneHotEncoder__gender_Male,OrdinalEncoder__parental_education,StandardScaler__study_time_hours,StandardScaler__attendance_percent,StandardScaler__sleep_hours,StandardScaler__internet_access,StandardScaler__extracurricular_activities,StandardScaler__part_time_job,StandardScaler__previous_grade,StandardScaler__final_exam_score
0,0.0,1.0,0.0,-0.614146,-1.280612,0.712201,0.410152,-1.191367,1.422742,-1.142853,-1.907532
1,1.0,0.0,1.0,0.997081,-1.419354,-0.981096,0.410152,0.839372,-0.702868,-1.487469,-0.331842
2,0.0,1.0,1.0,-0.345608,1.600957,-0.727102,0.410152,-1.191367,-0.702868,-1.703856,-0.815183
3,1.0,0.0,2.0,0.057199,-1.846253,-0.811767,0.410152,0.839372,1.422742,-1.687827,-1.201855
4,1.0,0.0,1.0,0.460005,0.085465,-0.473107,0.410152,0.839372,-0.702868,-0.028862,0.634839

In [46]:
class StudentDataset(Dataset):
    def __init__(self,X,y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self,idx):
        features = torch.tensor(self.X[idx],dtype=torch.float32)
        target = torch.tensor(self.y.values[idx],dtype=torch.long)
        return features,target

In [47]:
dataset = StudentDataset(X_train,y_train)
dataloader = DataLoader(dataset,batch_size = 32,shuffle = True,num_workers = 4)

In [48]:
for batch_idx,(features,targets) in enumerate(dataloader):
    print(f"Batch {batch_idx + 1}")
    print("Features : ",features.shape)
    print("Targets : ",targets.shape)
    break

Batch 1
Features :  torch.Size([32, 11])
Targets :  torch.Size([32])

In [49]:
class StudentPerformanceClassifier(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(StudentPerformanceClassifier,self).__init__()

        self.network=nn.Sequential(
            nn.Linear(input_dim,128),
            nn.Dropout(p=0.2),
            nn.ReLU(),
            nn.Linear(128,32),
            nn.Dropout(p=0.2),
            nn.ReLU(),
            nn.Linear(32,output_dim),
            nn.Softmax()
        )

    def forward(self,x):
        return self.network(x)

In [50]:
input_dim = X_train.shape[1]
output_dim = 5

In [51]:
model = StudentPerformanceClassifier(input_dim,output_dim)

In [52]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.01)

In [53]:
print(model)

StudentPerformanceClassifier(
  (network): Sequential(
    (0): Linear(in_features=11, out_features=128, bias=True)
    (1): Dropout(p=0.2, inplace=False)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=32, bias=True)
    (4): Dropout(p=0.2, inplace=False)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=5, bias=True)
    (7): Softmax(dim=None)
  )
)

In [54]:
train_dataset = StudentDataset(X_train,y_train)
test_dataset = StudentDataset(X_test,y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [55]:
epochs=500
for epoch in range(epochs):

    
    model.train()
    train_correct = 0
    train_total = 0

    for batch_X, batch_y in train_loader:

        optimizer.zero_grad()

        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)

        loss.backward()
        optimizer.step()

        predicted = outputs.argmax(dim=1)

        train_correct += (predicted == batch_y).sum().item()
        train_total += batch_y.size(0)

    train_acc = 100 * train_correct / train_total

    # Testing
    model.eval()
    test_correct = 0
    test_total = 0

    with torch.no_grad():
        for batch_X, batch_y in test_loader:

            outputs = model(batch_X)
            predicted = outputs.argmax(dim=1)

            test_correct += (predicted == batch_y).sum().item()
            test_total += batch_y.size(0)

    test_acc = 100 * test_correct / test_total

    print(
        f"Epoch [{epoch+1}/{epochs}] "
        f"Loss: {loss.item():.4f} "
        f"Train Acc: {train_acc:.2f}% "
        f"Test Acc: {test_acc:.2f}%"
    )

Epoch [1/500] Loss: 1.2315 Train Acc: 55.33% Test Acc: 74.80%
Epoch [2/500] Loss: 1.2014 Train Acc: 75.07% Test Acc: 80.80%

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1776: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)

Epoch [3/500] Loss: 0.9899 Train Acc: 81.87% Test Acc: 78.40%
Epoch [4/500] Loss: 1.0022 Train Acc: 82.00% Test Acc: 82.00%
Epoch [5/500] Loss: 1.1144 Train Acc: 82.00% Test Acc: 80.80%
Epoch [6/500] Loss: 1.1158 Train Acc: 82.40% Test Acc: 79.60%
Epoch [7/500] Loss: 1.0195 Train Acc: 84.40% Test Acc: 81.20%
Epoch [8/500] Loss: 1.1381 Train Acc: 83.73% Test Acc: 82.40%
Epoch [9/500] Loss: 1.0839 Train Acc: 84.53% Test Acc: 81.60%
Epoch [10/500] Loss: 1.2629 Train Acc: 84.80% Test Acc: 79.60%
Epoch [11/500] Loss: 0.9908 Train Acc: 85.20% Test Acc: 82.80%
Epoch [12/500] Loss: 0.9955 Train Acc: 86.40% Test Acc: 80.00%
Epoch [13/500] Loss: 1.1014 Train Acc: 84.13% Test Acc: 81.20%
Epoch [14/500] Loss: 1.0466 Train Acc: 80.27% Test Acc: 79.20%
Epoch [15/500] Loss: 1.1871 Train Acc: 85.20% Test Acc: 79.20%
Epoch [16/500] Loss: 1.0157 Train Acc: 83.47% Test Acc: 76.80%
Epoch [17/500] Loss: 1.1191 Train Acc: 81.60% Test Acc: 80.00%
Epoch [18/500] Loss: 1.0485 Train Acc: 84.40% Test Acc: 81.20%
Epoch [19/500] Loss: 1.0478 Train Acc: 85.33% Test Acc: 80.80%
Epoch [20/500] Loss: 0.9048 Train Acc: 86.67% Test Acc: 80.40%
Epoch [21/500] Loss: 1.0491 Train Acc: 84.80% Test Acc: 82.80%
Epoch [22/500] Loss: 0.9763 Train Acc: 86.00% Test Acc: 82.00%
Epoch [23/500] Loss: 0.9763 Train Acc: 85.20% Test Acc: 84.40%
Epoch [24/500] Loss: 0.9058 Train Acc: 85.87% Test Acc: 80.00%
Epoch [25/500] Loss: 1.1191 Train Acc: 83.60% Test Acc: 81.60%
Epoch [26/500] Loss: 1.0477 Train Acc: 84.27% Test Acc: 79.60%
Epoch [27/500] Loss: 1.1191 Train Acc: 84.53% Test Acc: 80.80%
Epoch [28/500] Loss: 1.0477 Train Acc: 85.20% Test Acc: 81.20%
Epoch [29/500] Loss: 0.9048 Train Acc: 85.73% Test Acc: 82.80%
Epoch [30/500] Loss: 0.9927 Train Acc: 87.60% Test Acc: 82.00%
Epoch [31/500] Loss: 1.1191 Train Acc: 84.27% Test Acc: 80.40%
Epoch [32/500] Loss: 0.9546 Train Acc: 85.20% Test Acc: 79.60%
Epoch [33/500] Loss: 0.9048 Train Acc: 87.33% Test Acc: 82.40%
Epoch [34/500] Loss: 0.9048 Train Acc: 87.07% Test Acc: 82.40%
Epoch [35/500] Loss: 1.0477 Train Acc: 87.33% Test Acc: 80.80%
Epoch [36/500] Loss: 1.1191 Train Acc: 85.87% Test Acc: 79.20%
Epoch [37/500] Loss: 0.9048 Train Acc: 84.93% Test Acc: 82.80%
Epoch [38/500] Loss: 1.0973 Train Acc: 85.07% Test Acc: 80.00%
Epoch [39/500] Loss: 0.9763 Train Acc: 82.80% Test Acc: 78.00%
Epoch [40/500] Loss: 1.0490 Train Acc: 82.80% Test Acc: 78.80%
Epoch [41/500] Loss: 1.1880 Train Acc: 83.33% Test Acc: 78.40%
Epoch [42/500] Loss: 1.1190 Train Acc: 83.60% Test Acc: 81.60%
Epoch [43/500] Loss: 1.0478 Train Acc: 84.93% Test Acc: 80.80%
Epoch [44/500] Loss: 1.1518 Train Acc: 85.60% Test Acc: 82.00%
Epoch [45/500] Loss: 1.0868 Train Acc: 82.67% Test Acc: 82.40%
Epoch [46/500] Loss: 1.0185 Train Acc: 82.80% Test Acc: 76.80%
Epoch [47/500] Loss: 1.1192 Train Acc: 82.80% Test Acc: 76.80%
Epoch [48/500] Loss: 0.9764 Train Acc: 79.47% Test Acc: 78.80%
Epoch [49/500] Loss: 0.9048 Train Acc: 84.53% Test Acc: 77.60%
Epoch [50/500] Loss: 1.1191 Train Acc: 84.40% Test Acc: 80.40%
Epoch [51/500] Loss: 1.1191 Train Acc: 83.47% Test Acc: 78.40%
Epoch [52/500] Loss: 1.3335 Train Acc: 83.07% Test Acc: 76.80%
Epoch [53/500] Loss: 1.1904 Train Acc: 82.40% Test Acc: 78.80%
Epoch [54/500] Loss: 1.1906 Train Acc: 84.13% Test Acc: 81.60%
Epoch [55/500] Loss: 1.0477 Train Acc: 84.93% Test Acc: 82.00%
Epoch [56/500] Loss: 1.1191 Train Acc: 86.00% Test Acc: 80.80%
Epoch [57/500] Loss: 0.9763 Train Acc: 83.20% Test Acc: 81.20%
Epoch [58/500] Loss: 0.9788 Train Acc: 83.60% Test Acc: 80.40%
Epoch [59/500] Loss: 0.9763 Train Acc: 81.07% Test Acc: 74.80%
Epoch [60/500] Loss: 0.9048 Train Acc: 81.33% Test Acc: 78.80%
Epoch [61/500] Loss: 1.0476 Train Acc: 81.60% Test Acc: 80.00%
Epoch [62/500] Loss: 1.1191 Train Acc: 82.93% Test Acc: 77.60%
Epoch [63/500] Loss: 1.1905 Train Acc: 81.60% Test Acc: 77.20%
Epoch [64/500] Loss: 1.1181 Train Acc: 83.07% Test Acc: 78.40%
Epoch [65/500] Loss: 1.1168 Train Acc: 83.87% Test Acc: 78.40%
Epoch [66/500] Loss: 1.0477 Train Acc: 84.00% Test Acc: 78.40%
Epoch [67/500] Loss: 1.1905 Train Acc: 83.20% Test Acc: 78.80%
Epoch [68/500] Loss: 0.9048 Train Acc: 83.87% Test Acc: 79.20%
Epoch [69/500] Loss: 1.0477 Train Acc: 83.47% Test Acc: 78.40%
Epoch [70/500] Loss: 1.1191 Train Acc: 83.60% Test Acc: 80.00%
Epoch [71/500] Loss: 1.0477 Train Acc: 81.73% Test Acc: 76.40%
Epoch [72/500] Loss: 0.9048 Train Acc: 80.93% Test Acc: 80.40%
Epoch [73/500] Loss: 0.9763 Train Acc: 82.93% Test Acc: 76.40%
Epoch [74/500] Loss: 0.9763 Train Acc: 83.20% Test Acc: 78.80%
Epoch [75/500] Loss: 1.1191 Train Acc: 80.53% Test Acc: 80.00%
Epoch [76/500] Loss: 1.3334 Train Acc: 82.93% Test Acc: 79.20%
Epoch [77/500] Loss: 1.1191 Train Acc: 84.93% Test Acc: 79.60%
Epoch [78/500] Loss: 1.1191 Train Acc: 84.93% Test Acc: 77.20%
Epoch [79/500] Loss: 1.0477 Train Acc: 84.40% Test Acc: 79.20%
Epoch [80/500] Loss: 1.1191 Train Acc: 82.53% Test Acc: 79.20%
Epoch [81/500] Loss: 1.0477 Train Acc: 86.13% Test Acc: 82.40%
Epoch [82/500] Loss: 0.9763 Train Acc: 85.20% Test Acc: 81.20%
Epoch [83/500] Loss: 0.9763 Train Acc: 84.93% Test Acc: 80.40%
Epoch [84/500] Loss: 1.1191 Train Acc: 83.07% Test Acc: 78.40%
Epoch [85/500] Loss: 1.0479 Train Acc: 83.87% Test Acc: 75.20%
Epoch [86/500] Loss: 1.1905 Train Acc: 84.80% Test Acc: 77.20%
Epoch [87/500] Loss: 1.2620 Train Acc: 78.27% Test Acc: 77.60%
Epoch [88/500] Loss: 1.0477 Train Acc: 83.07% Test Acc: 78.00%
Epoch [89/500] Loss: 1.0477 Train Acc: 84.40% Test Acc: 77.60%
Epoch [90/500] Loss: 1.0477 Train Acc: 83.33% Test Acc: 79.60%
Epoch [91/500] Loss: 1.2618 Train Acc: 82.53% Test Acc: 79.20%
Epoch [92/500] Loss: 1.2458 Train Acc: 82.53% Test Acc: 79.60%
Epoch [93/500] Loss: 0.9763 Train Acc: 82.80% Test Acc: 79.20%
Epoch [94/500] Loss: 1.0477 Train Acc: 82.27% Test Acc: 76.80%
Epoch [95/500] Loss: 1.1191 Train Acc: 83.73% Test Acc: 76.40%
Epoch [96/500] Loss: 1.1191 Train Acc: 82.93% Test Acc: 76.00%
Epoch [97/500] Loss: 1.3334 Train Acc: 83.47% Test Acc: 77.20%
Epoch [98/500] Loss: 0.9763 Train Acc: 83.47% Test Acc: 77.60%
Epoch [99/500] Loss: 0.9763 Train Acc: 82.53% Test Acc: 78.00%
Epoch [100/500] Loss: 1.1191 Train Acc: 83.87% Test Acc: 79.20%
Epoch [101/500] Loss: 0.9763 Train Acc: 82.93% Test Acc: 79.20%
Epoch [102/500] Loss: 1.1895 Train Acc: 82.80% Test Acc: 76.40%
Epoch [103/500] Loss: 1.0477 Train Acc: 80.93% Test Acc: 77.20%
Epoch [104/500] Loss: 0.9763 Train Acc: 79.73% Test Acc: 78.00%
Epoch [105/500] Loss: 1.0477 Train Acc: 82.00% Test Acc: 78.80%
Epoch [106/500] Loss: 1.0477 Train Acc: 83.47% Test Acc: 78.40%
Epoch [107/500] Loss: 1.0477 Train Acc: 82.93% Test Acc: 79.20%
Epoch [108/500] Loss: 1.1191 Train Acc: 81.47% Test Acc: 74.40%
Epoch [109/500] Loss: 1.2620 Train Acc: 83.07% Test Acc: 79.20%
Epoch [110/500] Loss: 1.0477 Train Acc: 84.80% Test Acc: 80.00%
Epoch [111/500] Loss: 1.1191 Train Acc: 85.33% Test Acc: 77.60%
Epoch [112/500] Loss: 1.0555 Train Acc: 82.27% Test Acc: 80.80%
Epoch [113/500] Loss: 0.9048 Train Acc: 85.20% Test Acc: 80.40%
Epoch [114/500] Loss: 1.1905 Train Acc: 84.40% Test Acc: 80.80%
Epoch [115/500] Loss: 1.0477 Train Acc: 85.33% Test Acc: 81.20%
Epoch [116/500] Loss: 1.0476 Train Acc: 84.53% Test Acc: 81.20%
Epoch [117/500] Loss: 0.9999 Train Acc: 85.73% Test Acc: 81.20%
Epoch [118/500] Loss: 1.1905 Train Acc: 85.07% Test Acc: 80.80%
Epoch [119/500] Loss: 0.9763 Train Acc: 83.73% Test Acc: 81.20%
Epoch [120/500] Loss: 1.1905 Train Acc: 84.00% Test Acc: 80.40%
Epoch [121/500] Loss: 1.0477 Train Acc: 84.27% Test Acc: 79.60%
Epoch [122/500] Loss: 1.0477 Train Acc: 84.80% Test Acc: 78.40%
Epoch [123/500] Loss: 1.0477 Train Acc: 84.67% Test Acc: 79.20%
Epoch [124/500] Loss: 0.9048 Train Acc: 84.93% Test Acc: 80.80%
Epoch [125/500] Loss: 1.1904 Train Acc: 84.80% Test Acc: 82.00%
Epoch [126/500] Loss: 0.9048 Train Acc: 85.33% Test Acc: 81.60%
Epoch [127/500] Loss: 1.1191 Train Acc: 84.40% Test Acc: 81.20%
Epoch [128/500] Loss: 1.1905 Train Acc: 84.93% Test Acc: 81.60%
Epoch [129/500] Loss: 1.0477 Train Acc: 85.73% Test Acc: 78.80%
Epoch [130/500] Loss: 0.9048 Train Acc: 83.20% Test Acc: 79.20%
Epoch [131/500] Loss: 0.9763 Train Acc: 83.60% Test Acc: 79.60%
Epoch [132/500] Loss: 1.0478 Train Acc: 82.00% Test Acc: 77.60%
Epoch [133/500] Loss: 1.1905 Train Acc: 82.27% Test Acc: 78.80%
Epoch [134/500] Loss: 1.0477 Train Acc: 83.20% Test Acc: 78.80%
Epoch [135/500] Loss: 0.9048 Train Acc: 84.67% Test Acc: 80.80%
Epoch [136/500] Loss: 0.9048 Train Acc: 85.20% Test Acc: 80.80%
Epoch [137/500] Loss: 1.1191 Train Acc: 85.20% Test Acc: 79.60%
Epoch [138/500] Loss: 1.0477 Train Acc: 82.80% Test Acc: 77.20%
Epoch [139/500] Loss: 1.3334 Train Acc: 81.87% Test Acc: 78.40%
Epoch [140/500] Loss: 1.2620 Train Acc: 83.47% Test Acc: 78.00%
Epoch [141/500] Loss: 1.1191 Train Acc: 79.73% Test Acc: 76.80%
Epoch [142/500] Loss: 0.9763 Train Acc: 78.53% Test Acc: 74.40%
Epoch [143/500] Loss: 0.9048 Train Acc: 81.60% Test Acc: 78.00%
Epoch [144/500] Loss: 1.1905 Train Acc: 82.93% Test Acc: 78.80%
Epoch [145/500] Loss: 1.1189 Train Acc: 83.73% Test Acc: 78.80%
Epoch [146/500] Loss: 0.9763 Train Acc: 83.87% Test Acc: 78.80%
Epoch [147/500] Loss: 1.2620 Train Acc: 80.67% Test Acc: 76.40%
Epoch [148/500] Loss: 1.0477 Train Acc: 80.27% Test Acc: 76.40%
Epoch [149/500] Loss: 1.1196 Train Acc: 83.87% Test Acc: 78.00%
Epoch [150/500] Loss: 1.0477 Train Acc: 82.53% Test Acc: 77.20%
Epoch [151/500] Loss: 1.0477 Train Acc: 83.20% Test Acc: 76.00%
Epoch [152/500] Loss: 1.1191 Train Acc: 81.33% Test Acc: 76.40%
Epoch [153/500] Loss: 0.9763 Train Acc: 83.73% Test Acc: 76.80%
Epoch [154/500] Loss: 1.0477 Train Acc: 82.93% Test Acc: 73.60%
Epoch [155/500] Loss: 1.0477 Train Acc: 81.20% Test Acc: 75.60%
Epoch [156/500] Loss: 1.2620 Train Acc: 83.60% Test Acc: 76.40%
Epoch [157/500] Loss: 0.9763 Train Acc: 81.07% Test Acc: 78.40%
Epoch [158/500] Loss: 1.0477 Train Acc: 83.33% Test Acc: 76.80%
Epoch [159/500] Loss: 1.1905 Train Acc: 81.60% Test Acc: 77.60%
Epoch [160/500] Loss: 1.0336 Train Acc: 81.87% Test Acc: 78.40%
Epoch [161/500] Loss: 1.1191 Train Acc: 80.13% Test Acc: 75.20%
Epoch [162/500] Loss: 1.1191 Train Acc: 77.73% Test Acc: 74.00%
Epoch [163/500] Loss: 1.0477 Train Acc: 77.73% Test Acc: 74.00%
Epoch [164/500] Loss: 1.2620 Train Acc: 80.13% Test Acc: 78.00%
Epoch [165/500] Loss: 0.9048 Train Acc: 81.07% Test Acc: 75.60%
Epoch [166/500] Loss: 1.0477 Train Acc: 80.40% Test Acc: 77.20%
Epoch [167/500] Loss: 1.4048 Train Acc: 82.27% Test Acc: 78.00%
Epoch [168/500] Loss: 0.9763 Train Acc: 80.93% Test Acc: 79.60%
Epoch [169/500] Loss: 1.0477 Train Acc: 81.73% Test Acc: 79.20%
Epoch [170/500] Loss: 1.0477 Train Acc: 81.87% Test Acc: 78.80%
Epoch [171/500] Loss: 1.3334 Train Acc: 81.20% Test Acc: 80.40%
Epoch [172/500] Loss: 0.9048 Train Acc: 82.67% Test Acc: 78.80%
Epoch [173/500] Loss: 1.0477 Train Acc: 82.13% Test Acc: 78.80%
Epoch [174/500] Loss: 1.0732 Train Acc: 83.87% Test Acc: 77.20%
Epoch [175/500] Loss: 0.9765 Train Acc: 81.47% Test Acc: 75.60%
Epoch [176/500] Loss: 1.2620 Train Acc: 79.73% Test Acc: 76.40%
Epoch [177/500] Loss: 1.0477 Train Acc: 81.20% Test Acc: 75.20%
Epoch [178/500] Loss: 1.1905 Train Acc: 80.00% Test Acc: 76.80%
Epoch [179/500] Loss: 1.2620 Train Acc: 75.07% Test Acc: 71.20%
Epoch [180/500] Loss: 0.9763 Train Acc: 75.20% Test Acc: 73.20%
Epoch [181/500] Loss: 1.1191 Train Acc: 77.60% Test Acc: 73.60%
Epoch [182/500] Loss: 1.1905 Train Acc: 74.80% Test Acc: 72.40%
Epoch [183/500] Loss: 1.2620 Train Acc: 75.33% Test Acc: 73.20%
Epoch [184/500] Loss: 1.2620 Train Acc: 81.33% Test Acc: 74.80%
Epoch [185/500] Loss: 0.9763 Train Acc: 81.87% Test Acc: 80.80%
Epoch [186/500] Loss: 1.1191 Train Acc: 83.87% Test Acc: 79.20%
Epoch [187/500] Loss: 0.9048 Train Acc: 84.13% Test Acc: 80.00%
Epoch [188/500] Loss: 0.9763 Train Acc: 84.40% Test Acc: 78.80%
Epoch [189/500] Loss: 0.9048 Train Acc: 82.53% Test Acc: 78.00%
Epoch [190/500] Loss: 0.9763 Train Acc: 83.07% Test Acc: 80.40%
Epoch [191/500] Loss: 0.9763 Train Acc: 81.87% Test Acc: 79.20%
Epoch [192/500] Loss: 1.1191 Train Acc: 82.53% Test Acc: 80.00%
Epoch [193/500] Loss: 0.9763 Train Acc: 82.80% Test Acc: 80.40%
Epoch [194/500] Loss: 1.0477 Train Acc: 83.73% Test Acc: 82.00%
Epoch [195/500] Loss: 1.0477 Train Acc: 84.53% Test Acc: 80.80%
Epoch [196/500] Loss: 1.0477 Train Acc: 83.33% Test Acc: 81.60%
Epoch [197/500] Loss: 0.9763 Train Acc: 81.33% Test Acc: 78.80%
Epoch [198/500] Loss: 1.0477 Train Acc: 82.93% Test Acc: 80.40%
Epoch [199/500] Loss: 1.1905 Train Acc: 83.73% Test Acc: 82.40%
Epoch [200/500] Loss: 0.9763 Train Acc: 82.40% Test Acc: 82.00%
Epoch [201/500] Loss: 1.1191 Train Acc: 83.87% Test Acc: 82.00%
Epoch [202/500] Loss: 0.9763 Train Acc: 84.00% Test Acc: 83.60%
Epoch [203/500] Loss: 1.0477 Train Acc: 84.93% Test Acc: 82.00%
Epoch [204/500] Loss: 1.1191 Train Acc: 84.00% Test Acc: 81.20%
Epoch [205/500] Loss: 1.1191 Train Acc: 83.60% Test Acc: 81.60%
Epoch [206/500] Loss: 1.0477 Train Acc: 82.27% Test Acc: 79.20%
Epoch [207/500] Loss: 1.0477 Train Acc: 82.00% Test Acc: 78.40%
Epoch [208/500] Loss: 1.1191 Train Acc: 82.13% Test Acc: 79.60%
Epoch [209/500] Loss: 1.1905 Train Acc: 82.13% Test Acc: 80.40%
Epoch [210/500] Loss: 1.1905 Train Acc: 84.13% Test Acc: 80.40%
Epoch [211/500] Loss: 1.0477 Train Acc: 84.67% Test Acc: 80.40%
Epoch [212/500] Loss: 0.9048 Train Acc: 84.27% Test Acc: 80.40%
Epoch [213/500] Loss: 1.0477 Train Acc: 83.33% Test Acc: 80.40%
Epoch [214/500] Loss: 1.1191 Train Acc: 85.20% Test Acc: 80.00%
Epoch [215/500] Loss: 0.9763 Train Acc: 85.07% Test Acc: 79.20%
Epoch [216/500] Loss: 0.9763 Train Acc: 83.87% Test Acc: 78.80%
Epoch [217/500] Loss: 1.1191 Train Acc: 83.33% Test Acc: 82.00%
Epoch [218/500] Loss: 1.1191 Train Acc: 86.13% Test Acc: 81.60%
Epoch [219/500] Loss: 1.0477 Train Acc: 85.87% Test Acc: 79.60%
Epoch [220/500] Loss: 1.1833 Train Acc: 84.00% Test Acc: 79.60%
Epoch [221/500] Loss: 1.1191 Train Acc: 82.67% Test Acc: 77.60%
Epoch [222/500] Loss: 1.4763 Train Acc: 83.87% Test Acc: 79.60%
Epoch [223/500] Loss: 0.9763 Train Acc: 83.33% Test Acc: 78.80%
Epoch [224/500] Loss: 0.9763 Train Acc: 82.67% Test Acc: 78.00%
Epoch [225/500] Loss: 1.1191 Train Acc: 82.27% Test Acc: 79.20%
Epoch [226/500] Loss: 1.0477 Train Acc: 82.00% Test Acc: 80.40%
Epoch [227/500] Loss: 1.1191 Train Acc: 81.07% Test Acc: 78.00%
Epoch [228/500] Loss: 1.1905 Train Acc: 82.00% Test Acc: 80.80%
Epoch [229/500] Loss: 1.1908 Train Acc: 82.67% Test Acc: 78.00%
Epoch [230/500] Loss: 1.0477 Train Acc: 81.60% Test Acc: 77.20%
Epoch [231/500] Loss: 1.1243 Train Acc: 81.73% Test Acc: 79.20%
Epoch [232/500] Loss: 0.9763 Train Acc: 83.33% Test Acc: 79.20%
Epoch [233/500] Loss: 1.0477 Train Acc: 83.07% Test Acc: 79.20%
Epoch [234/500] Loss: 1.0477 Train Acc: 83.07% Test Acc: 79.60%
Epoch [235/500] Loss: 1.0477 Train Acc: 83.87% Test Acc: 80.00%
Epoch [236/500] Loss: 1.1191 Train Acc: 83.47% Test Acc: 80.00%
Epoch [237/500] Loss: 0.9763 Train Acc: 84.67% Test Acc: 80.80%
Epoch [238/500] Loss: 0.9048 Train Acc: 84.27% Test Acc: 80.80%
Epoch [239/500] Loss: 1.2460 Train Acc: 85.47% Test Acc: 81.20%
Epoch [240/500] Loss: 1.1191 Train Acc: 83.33% Test Acc: 76.80%
Epoch [241/500] Loss: 0.9763 Train Acc: 80.40% Test Acc: 76.80%
Epoch [242/500] Loss: 1.0477 Train Acc: 81.33% Test Acc: 78.00%
Epoch [243/500] Loss: 1.1191 Train Acc: 81.47% Test Acc: 80.80%
Epoch [244/500] Loss: 1.2620 Train Acc: 82.93% Test Acc: 81.60%
Epoch [245/500] Loss: 1.0477 Train Acc: 83.87% Test Acc: 81.20%
Epoch [246/500] Loss: 1.2620 Train Acc: 84.13% Test Acc: 81.60%
Epoch [247/500] Loss: 1.1191 Train Acc: 83.60% Test Acc: 80.80%
Epoch [248/500] Loss: 0.9048 Train Acc: 82.53% Test Acc: 80.00%
Epoch [249/500] Loss: 1.1175 Train Acc: 84.53% Test Acc: 78.40%
Epoch [250/500] Loss: 1.1191 Train Acc: 84.27% Test Acc: 79.60%
Epoch [251/500] Loss: 1.0477 Train Acc: 81.47% Test Acc: 78.40%
Epoch [252/500] Loss: 1.1191 Train Acc: 81.20% Test Acc: 78.80%
Epoch [253/500] Loss: 1.1905 Train Acc: 82.40% Test Acc: 79.20%
Epoch [254/500] Loss: 1.1191 Train Acc: 78.80% Test Acc: 76.40%
Epoch [255/500] Loss: 1.1191 Train Acc: 79.87% Test Acc: 76.40%
Epoch [256/500] Loss: 1.1619 Train Acc: 80.53% Test Acc: 81.20%
Epoch [257/500] Loss: 1.1754 Train Acc: 80.80% Test Acc: 76.80%
Epoch [258/500] Loss: 1.1058 Train Acc: 81.60% Test Acc: 80.80%
Epoch [259/500] Loss: 1.0477 Train Acc: 80.53% Test Acc: 78.00%
Epoch [260/500] Loss: 0.9779 Train Acc: 79.73% Test Acc: 77.60%
Epoch [261/500] Loss: 1.1905 Train Acc: 78.80% Test Acc: 78.40%
Epoch [262/500] Loss: 0.9763 Train Acc: 80.13% Test Acc: 79.60%
Epoch [263/500] Loss: 1.1191 Train Acc: 82.53% Test Acc: 79.60%
Epoch [264/500] Loss: 1.3334 Train Acc: 80.67% Test Acc: 79.60%
Epoch [265/500] Loss: 0.9048 Train Acc: 80.93% Test Acc: 78.80%
Epoch [266/500] Loss: 1.1191 Train Acc: 81.73% Test Acc: 78.80%
Epoch [267/500] Loss: 1.0477 Train Acc: 82.00% Test Acc: 80.40%
Epoch [268/500] Loss: 1.0477 Train Acc: 81.73% Test Acc: 80.40%
Epoch [269/500] Loss: 0.9763 Train Acc: 82.53% Test Acc: 80.00%
Epoch [270/500] Loss: 1.3334 Train Acc: 82.27% Test Acc: 79.60%
Epoch [271/500] Loss: 0.9763 Train Acc: 82.80% Test Acc: 80.40%
Epoch [272/500] Loss: 1.1191 Train Acc: 81.60% Test Acc: 77.60%
Epoch [273/500] Loss: 1.1905 Train Acc: 81.07% Test Acc: 77.60%
Epoch [274/500] Loss: 1.0477 Train Acc: 80.93% Test Acc: 77.60%
Epoch [275/500] Loss: 1.3334 Train Acc: 78.93% Test Acc: 74.80%
Epoch [276/500] Loss: 1.1191 Train Acc: 78.53% Test Acc: 74.80%
Epoch [277/500] Loss: 1.1191 Train Acc: 77.47% Test Acc: 74.80%
Epoch [278/500] Loss: 1.0477 Train Acc: 78.40% Test Acc: 74.80%
Epoch [279/500] Loss: 1.0477 Train Acc: 79.60% Test Acc: 78.80%
Epoch [280/500] Loss: 1.0477 Train Acc: 81.20% Test Acc: 79.60%
Epoch [281/500] Loss: 0.9763 Train Acc: 80.53% Test Acc: 78.80%
Epoch [282/500] Loss: 1.0477 Train Acc: 82.53% Test Acc: 82.00%
Epoch [283/500] Loss: 0.9763 Train Acc: 83.33% Test Acc: 81.60%
Epoch [284/500] Loss: 0.9763 Train Acc: 84.13% Test Acc: 81.60%
Epoch [285/500] Loss: 1.1191 Train Acc: 84.27% Test Acc: 81.60%
Epoch [286/500] Loss: 1.2620 Train Acc: 83.07% Test Acc: 81.60%
Epoch [287/500] Loss: 0.9763 Train Acc: 83.33% Test Acc: 80.80%
Epoch [288/500] Loss: 0.9763 Train Acc: 82.93% Test Acc: 80.40%
Epoch [289/500] Loss: 1.1191 Train Acc: 82.27% Test Acc: 80.40%
Epoch [290/500] Loss: 1.1909 Train Acc: 82.93% Test Acc: 81.20%
Epoch [291/500] Loss: 1.1905 Train Acc: 83.07% Test Acc: 79.60%
Epoch [292/500] Loss: 1.1191 Train Acc: 82.27% Test Acc: 78.80%
Epoch [293/500] Loss: 1.0477 Train Acc: 81.60% Test Acc: 79.60%
Epoch [294/500] Loss: 1.1191 Train Acc: 81.47% Test Acc: 79.60%
Epoch [295/500] Loss: 1.1905 Train Acc: 82.27% Test Acc: 79.20%
Epoch [296/500] Loss: 1.1905 Train Acc: 83.07% Test Acc: 80.00%
Epoch [297/500] Loss: 1.0477 Train Acc: 82.93% Test Acc: 80.00%
Epoch [298/500] Loss: 1.1905 Train Acc: 81.33% Test Acc: 80.40%
Epoch [299/500] Loss: 1.1905 Train Acc: 82.67% Test Acc: 79.60%
Epoch [300/500] Loss: 0.9048 Train Acc: 81.73% Test Acc: 80.40%
Epoch [301/500] Loss: 1.1905 Train Acc: 83.07% Test Acc: 80.80%
Epoch [302/500] Loss: 1.0477 Train Acc: 83.33% Test Acc: 80.80%
Epoch [303/500] Loss: 1.1191 Train Acc: 83.07% Test Acc: 80.80%
Epoch [304/500] Loss: 1.1191 Train Acc: 83.33% Test Acc: 80.00%
Epoch [305/500] Loss: 1.1905 Train Acc: 83.87% Test Acc: 80.40%
Epoch [306/500] Loss: 1.1905 Train Acc: 84.00% Test Acc: 81.20%
Epoch [307/500] Loss: 0.9048 Train Acc: 83.33% Test Acc: 81.60%
Epoch [308/500] Loss: 1.0477 Train Acc: 84.80% Test Acc: 82.80%
Epoch [309/500] Loss: 0.9763 Train Acc: 86.00% Test Acc: 82.00%
Epoch [310/500] Loss: 0.9048 Train Acc: 84.40% Test Acc: 82.80%
Epoch [311/500] Loss: 1.1191 Train Acc: 84.13% Test Acc: 82.80%
Epoch [312/500] Loss: 0.9763 Train Acc: 84.93% Test Acc: 81.20%
Epoch [313/500] Loss: 1.1191 Train Acc: 82.40% Test Acc: 80.40%
Epoch [314/500] Loss: 1.0477 Train Acc: 84.80% Test Acc: 81.60%
Epoch [315/500] Loss: 1.1191 Train Acc: 85.73% Test Acc: 80.80%
Epoch [316/500] Loss: 1.0477 Train Acc: 83.87% Test Acc: 81.20%

In [56]:
model.eval()

correct = 0
total = 0

with torch.no_grad():
    for batch_X, batch_y in test_loader:

        outputs = model(batch_X)
        predicted = outputs.argmax(dim=1)

        correct += (predicted == batch_y).sum().item()
        total += batch_y.size(0)

test_acc = 100 * correct / total

print(f"Test Accuracy: {test_acc:.2f}%")

Test Accuracy: 78.00%